# Generated by Django 5.0.7 on 2024-07-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RouterBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.routerbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, max_length=50, null=True)),
                ('location_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location_floor', models.CharField(blank=True, max_length=50, null=True)),
                ('router_count', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_ports', models.CharField(blank=True, max_length=50, null=True)),
                ('connection_port', models.CharField(blank=True, max_length=50, null=True)),
                ('connected_router_location', models.CharField(blank=True, max_length=50, null=True)),
                ('loopback_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('vlan', models.CharField(blank=True, max_length=50, null=True)),
                ('connection', models.CharField(blank=True, max_length=50, null=True)),
                ('energy_type', models.CharField(blank=True, max_length=50, null=True)),
                ('temos', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.province')),
                ('connected_routers', models.ManyToManyField(blank=True, related_name='connected_devices', to='app.router')),
                ('router_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_devices', to='app.router')),
                ('router_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.routerbrand')),
            ],
        ),
    ]
